# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-30 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cropping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Farm_points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Farms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area', models.FloatField()),
                ('household_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.HouseHolds')),
            ],
        ),
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Wells',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Depth', models.FloatField()),
                ('point_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Points')),
            ],
        ),
        migrations.CreateModel(
            name='Yields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yields', models.FloatField()),
                ('date_last_recorded', models.DateField()),
                ('well_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Wells')),
            ],
        ),
        migrations.AddField(
            model_name='farm_points',
            name='farm_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Farms'),
        ),
        migrations.AddField(
            model_name='farm_points',
            name='point_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Points'),
        ),
        migrations.AddField(
            model_name='cropping',
            name='crop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Crops'),
        ),
        migrations.AddField(
            model_name='cropping',
            name='farm_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Farms'),
        ),
        migrations.AddField(
            model_name='cropping',
            name='season_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Seasons'),
        ),
    ]
